/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fuhbqtatyixpqrsyuozu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1aGJxdGF0eWl4cHFyc3l1b3p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxNjAzMTUsImV4cCI6MjA4NDczNjMxNX0.ds8Ap039dQm2LYUv0-79_1AtddeZ3-AO6czG6OuoTVM"